### PR TITLE
Variable launch timeout

### PR DESCRIPTION
**Pull request by pablopique**
Launch timeout of the application was too short and I implemented it to make it variable.

From the launch options now there is the possibility to overwrite the timeout and change it. If this statement is not used in the options launch the default value is 10000 like before.

### CODE REVIEW

**Comment by mprobst-irt** [comment]
I think it is a good contribution, but would prefer to keep the change backwards compatible. Rather than replacing a method with adding new arguments I prefer to overload the method so it would not break existing apps.

**Comment by pablopique** [comment]
Perfect, i will send you the pull request on Monday.

**Comment by mprobst-irt** [comment]
Thanks. Let's see what the author of the plugin thinks ;)

**Comment by louaybassbouss** [comment]
Thanks yes it makes sense to allow the App to configure the timeout but as @mprobst-irt mentioned it should be backward compatible.

**Comment by pablopique** [comment]
I protected new options to be backward compatible. It should not be problems in existing apps.

**Comment by mprobst-irt** [comment]
I am not sure whether this is backwards compatible, but I was expecting something like

public void launchApp(String appName, String launchData, String contentType, 
   JSONObject options, Dial.LaunchAppCallback launchAppCallback) {
   launchApp(appName, launchData, contentType, defaultTimeout, launchAppCallback);
}

public void launchApp(String appName, String launchData, String contentType, 
   int timeout, Dial.LaunchAppCallback launchAppCallback) {
   ...
}

IMHO, you should not remove any public methods with a specific signature.

**Comment by louaybassbouss** [comment]
@mprobst-irt you need to check the binding between Java and Javascript for methods with the same name `launchApp`.

**Comment by mprobst-irt** [comment]
@louaybassbouss ok, we were using the plugin in native Android apps, therefore I was focussing on the Java interface only.

@pablopique sorry for the confusion. Looking only from Javascript this is fine.

**Comment by pablopique** [comment]
I don't really understand your suggestions.

Now I am checking the binding in Java so if there is no options, it creates a new one with default values, so it would not be any problem if function launchApp is called in javascript without option.

If it needs any change, specify it, but i think it's all protected for existing apps.

Thanks

**Comment by mprobst-irt** [comment]
Never mind. Please go ahead, for the intended use within Cordova there is no issue.

We are using the Java part of this plugin in some projects (native Android), and you have replaced a method signature of launchApp, this will break a Java app.

**Comment by pablopique** [comment]
Sorry for the delay.

I overloaded LaunchApp public function to make it Java compatible, so it should work now.

**Comment by mprobst-irt** [comment]
thank you, Pablo

**Pull request merged**
